package com.demo.customers.application.service.mapper;

import org.springframework.stereotype.Component;
import java.time.Instant;

import com.demo.customers.application.model.command.CustomerCommand;
import com.demo.customers.application.model.command.input.AddressInput;
import com.demo.customers.application.model.command.input.CustomerTypeInput;
import com.demo.customers.domain.model.Address;
import com.demo.customers.domain.model.Customer;
import com.demo.customers.domain.model.CustomerType;

/**
 * Mapper component that converts commands and DTOs to domain models.
 */
@Component
public class CustomerCommandMapper {

    /**
     * Converts a CustomerCommand to a Customer domain model for creation.
     *
     * @param command   the customer command containing input data
     * @param createdAt the timestamp when the customer is created
     * @return a new Customer domain model ready for persistence
     */
    public Customer toDomain(CustomerCommand command, Instant createdAt) {
        return new Customer(
                null, // ID will be generated by the repository
                command.firstName(),
                command.lastName(),
                command.companyName(),
                command.birthDate(),
                command.vatNumber(),
                command.email(),
                command.phoneNumber(),
                toAddress(command.address()),
                toCustomerType(command.type()),
                createdAt,
                createdAt // For new customers, createdAt and updatedAt are the same
        );
    }

    /**
     * Converts a CustomerCommand to a Customer domain model for update.
     *
     * @param existing  the existing customer to be updated
     * @param command   the customer command containing updated data
     * @param updatedAt the timestamp when the customer is updated
     * @return an updated Customer domain model ready for persistence
     */
    public Customer toDomain(Customer existing, CustomerCommand command, Instant updatedAt) {
        return new Customer(
                existing.id(), // Preserve existing ID
                command.firstName(),
                command.lastName(),
                command.companyName(),
                command.birthDate(),
                command.vatNumber(),
                command.email(),
                command.phoneNumber(),
                toAddress(command.address()),
                toCustomerType(command.type()),
                existing.createdAt(), // Preserve original createdAt
                updatedAt
        );
    }

    /**
     * Converts AddressInput DTO to Address domain model.
     *
     * @param input the address input DTO
     * @return a new Address domain model
     */
    private Address toAddress(AddressInput input) {
        return new Address(
                input.street(),
                input.city(),
                input.postalCode(),
                input.region(),
                input.countryCode()
        );
    }

    /**
     * Converts CustomerTypeInput enum to CustomerType enum.
     *
     * @param input the customer type input
     * @return the corresponding domain customer type
     */
    private CustomerType toCustomerType(CustomerTypeInput input) {
        return switch (input) {
            case INDIVIDUAL -> CustomerType.INDIVIDUAL;
            case BUSINESS -> CustomerType.BUSINESS;
        };
    }
}